name: Deploy Executable
on:
  push:
    branches:
      - 'main'

jobs:
  binary:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ windows-latest, ubuntu-20.04, ubuntu-22.04]

    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
      - name: Generate antares-study-version executable
        run: |
          pyinstaller -F src/antares/study/version/__main__.py -n antares-study-version-$(1.0.0)-${{ matrix.os }}
      - name: Archive antares-study-version executable
        uses: actions/upload-artifact@v4
        with:
          path: dist/*