name: Lint
on:
  push:
    branches:
      - "**"

jobs:
  python-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Check code format (Ruff)
        run: ruff format --check src tests
      - name: Check Typing (mypy)
        run: |
          mypy --install-types --non-interactive