name: main
on:
  push:
    branches:
      - "**"

jobs:
  python-lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Check code format (Ruff)
        run: ruff format --check src tests
      - name: Check Typing (mypy)
        run: |
          mypy --install-types --non-interactive

  python-test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 9
      matrix:
        os: [windows-latest, ubuntu-20.04]
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      # Adapt the following code
      - name: Test with pytest
        run: |
          pytest --cov antarest --cov-report xml
      - name: Fix code coverage paths
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sed -i 's/\/home\/runner\/work\/AntaREST\/AntaREST/\/github\/workspace/g' coverage.xml
      - name: Archive code coverage results
        if: matrix.os == 'ubuntu-20.04'
        uses: actions/upload-artifact@v4
        with:
          name: python-code-coverage-report
          path: coverage.xml

  sonarcloud:
    runs-on: ubuntu-20.04
    needs: python-test
    steps:
      - uses: actions/checkout@v4
      - name: Download python coverage report
        uses: actions/download-artifact@v4
        with:
          name: python-code-coverage-report
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}